### PR TITLE
Fixed file structure under content so that submissions now reside und…

### PR DESCRIPTION
**Pull request by A-N-uraag**
…er respective content/submissions/participant/problem_id/ and Updated file name indexing and ordering on submissions page

### CODE REVIEW

**Comment by YashasAndaluri** [comment]
Need to fix submitted file paths for compilation and testing

**Comment by A-N-uraag** [comment]
Ohh right! Will start working on it. I had a look at the code and it may take some time to find and fix it at all the occurrences of $filename.

> Need to fix submitted file paths for compilation and testing

**Comment by YashasAndaluri** [comment]
> Ohh right! Will start working on it. I had a look at the code and it may take some time to find and fix it at all the occurrences of $filename.
> 
> > Need to fix submitted file paths for compilation and testing

Ok. I think main_compiler.sh, main_tester.sh and compile_and_test.py in content directory need to be changed.

**Comment by anilavakundu** [comment]
Hi both! Apologies for the delay in replying. I was neck-deep into assignments! Was this PR changed?

@A-N-uraag  Yashas is right you just need to change the scripts to point to the right paths as per the hierarchial changes in the new filesystem.  Try submitting into a contest after the changes if the compilation works(Along with compilation messages that should appear for public test cases (Read: #8 ) ) I think we can safely merge this then. 

We can meet if you still have doubts! :)

**Pull request closed without merging**
